name: pyro-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.2.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - bokeh=1.3.4=py37_0
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.9.11=py37_0
  - cffi=1.13.0=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - conda-package-handling=1.6.0=py37h516909a_0
  - cpuonly=1.0=0
  - cryptography=2.7=py37h72c5cf5_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he1b5a44_1004
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.40.1=h0f2764d_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - harfbuzz=2.4.0=h9f30f68_3
  - icu=64.2=he1b5a44_1
  - idna=2.8=py37_1000
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipython=7.8.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.1.1=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py37_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.0=hc9558a2_1
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libllvm9=9.0.0=hc9558a2_2
  - libopenblas=0.3.7=h6e990d7_2
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=hfc65ed5_1004
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.0=hebb1f50_0
  - libxml2=2.9.9=hee79883_5
  - lz4-c=1.8.3=he1b5a44_1001
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37he7580a8_1
  - mistune=0.8.4=py37h14c3975_1000
  - mkl=2019.4=243
  - more-itertools=7.2.0=py_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.9.0=h6bb024c_0
  - notebook=6.0.1=py37_0
  - nspr=4.20=hf484d3e_1000
  - nss=3.47=he751ad9_0
  - numpy=1.17.2=py37h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1c=h516909a_0
  - packaging=19.2=py_0
  - pandas=0.25.2=py37hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha030887_1
  - parso=0.5.1=py_0
  - pcre=8.43=he1b5a44_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.2.0=py37h6b7be26_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycosat=0.6.3=py37h14c3975_1001
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.12.3=py37hcca6a23_0
  - pyrsistent=0.15.4=py37h516909a_0
  - pysocks=1.7.1=py37_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - python-graphviz=0.13=py_0
  - pytorch=1.3.0=py3.7_cpu_0
  - pytz=2019.3=py_0
  - pyyaml=5.1.2=py37h516909a_0
  - pyzmq=18.1.0=py37h1768529_0
  - qt=5.12.5=h0c104cb_0
  - qtconsole=4.5.5=py_0
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - ruamel_yaml=0.15.71=py37h14c3975_1000
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.3.1=py37h921218d_2
  - send2trash=1.5.0=py_0
  - setuptools=41.4.0=py37_0
  - six=1.12.0=py37_1000
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1003
  - torchvision=0.4.1=py37_cpu
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.6=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h516909a_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.3=h3b9ef0a_0
  - pip:
    - corner==2.0.1
    - opt-einsum==3.1.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyro-ppl==0.4.1
prefix: /home/phuijse/miniconda3/envs/pyro-env

